name: Quartus Tests

'on':
    workflow_dispatch: {}
    push:
      paths:
      - src/**
      - .github/workflows/quartus_tests.yml
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
        - name: Check out code
          uses: actions/checkout@v3
        - name: Set up Quartus
          uses: pfeinsper/24a-CTI-RISCV@v1
        - name: Run Quartus tests
          run: |
            cd quartus
            quartus_map "top level"