name: Quartus Tests

'on':
    workflow_dispatch: {}
    push:
      paths:
      - src/**
      - .github/workflows/quartus_tests.yml
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file .devcontainer/Dockerfile --tag my-image-name:$(date +%s)
    - name: Syntesis
      run: docker run --rm my-image-name:$(date +%s) /bin/bash -c "cd /workspace/quartus && quartus_map "top_level""
    