name: Quartus Tests

'on':
    workflow_dispatch: {}
    push:
      paths:
      - src/**
      - .github/workflows/quartus_tests.yml
jobs:

  build:
    name: Build docker
    runs-on: ubuntu-latest
    container:
      image: chriz2600/quartus-lite:latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
            image: chriz2600/quartus-lite:latest
            options: -v ${{ github.workspace }}:/var/www
            run: |
              cd quartus
              quartus_map "top_level"