name: Quartus Tests

'on':
    workflow_dispatch: {}
    push:
      paths:
      - src/**
      - .github/workflows/quartus_tests.yml
jobs:

  build:

    runs-on: ubuntu-latest
    container:
      image: .devcontainer/Dockerfile
    steps:
    - uses: actions/checkout@v3
    - name: Syntesis
      run: cd quartus && quartus_map "top_level"
    