name: Quartus Tests

'on':
    workflow_dispatch: {}
    push:
      paths:
      - src/**
      - .github/workflows/quartus_tests.yml
jobs:

  build:
    name: Build docker
    runs-on: ubuntu-latest
    container:
      image: chriz2600/quartus-lite:latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - run: |
              cd quartus
              quartus_map "top_level"