name: Run tests
'on':
  workflow_dispatch: {}
  push:
    paths:
    - src/**
    - test/**
    - .github/workflows/vhd_tests.yml
jobs:
  setup-env:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install GHDL
      uses: ghdl/setup-ghdl-ci@nightly
      with:
        backend: llvm
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: pip
    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - name: GENERIC_ADDER test
      run: pytest -k GENERIC_ADDER

    - name: GENERIC_COUNTER test
      run: pytest -k GENERIC_COUNTER

    - name: GENERIC_DEBOUNCE test
      run: pytest -k GENERIC_DEBOUNCE
