name: VHD tests
'on':
  workflow_dispatch: {}
  push:
    paths:
    - src/**
    - test/**
    - .github/workflows/vhd_tests.yml

jobs:
  test:
    name: Test ${{ matrix.component }}
    runs-on: ubuntu-latest
    container:
      image: hdlc/ghdl:yosys
    strategy:
      matrix:
          include:
          - component: CPU_EXECUTION_FOWARDING_UNIT
            enabled: true
          - component: CPU_LOAD_EXTENDER
            enabled: true
          - component: CPU_STAGE_EX
            enabled: false
          - component: CPU_STAGE_ID
            enabled: false
          - component: CPU_STAGE_IF
            enabled: false
          - component: CPU_STAGE_MEM
            enabled: false
          - component: CPU_STAGE_WB
            enabled: false
          - component: CPU_STORE_EXTENDER
            enabled: false
          - component: CPU_TOP_LEVEL
            enabled: true
          - component: GENERIC_ADDER
            enabled: true
          - component: GENERIC_COMPARATOR
            enabled: true
          - component: GENERIC_DEBOUNCE
            enabled: true
          - component: GENERIC_EDGE_DETECTOR
            enabled: true
          - component: GENERIC_FLIP_FLOP
            enabled: true
          - component: GENERIC_MUX_2X1
            enabled: true
          - component: GENERIC_MUX_4X1
            enabled: true
          - component: GENERIC_RAM
            enabled: true
          - component: GENERIC_REGISTER
            enabled: true
          - component: GENERIC_ROM
            enabled: true
          - component: GENERIC_SIGNAL_EXTENDER
            enabled: true
          - component: MODULE_BRANCH_COMPARE_UNIT
            enabled: true
          - component: MODULE_BRANCH_UNIT
            enabled: true
          - component: MODULE_CONTROL_UNIT
            enabled: true
          - component: MODULE_EXECUTION_UNIT_CONTROLLER
            enabled: true
          - component: MODULE_EXECUTION_UNIT
            enabled: true
          - component: MODULE_PROGRAM_COUNTER
            enabled: true
          - component: MODULE_REGISTER_FILE
            enabled: true
          - component: MODULE_WRITE_BACK
            enabled: true
          - component: RV32I_ALU_BIT
            enabled: true
          - component: RV32I_ALU_CONTROLLER
            enabled: true
          - component: RV32I_ALU_SHIFTER
            enabled: true
          - component: RV32I_ALU
            enabled: true
          - component: RV32I_BRANCH_CONTROLLER
            enabled: true
          - component: RV32I_REGISTER_FILE
            enabled: true
          - component: TOP_LEVEL
            enabled: true
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        npm install -g netlistsvg
    - name: Run Synthesis
      run: pytest -k ${{ matrix.component }} -m synthesis
    - name: Run Testcases
      if: ${{ contains(matrix.enabled, true) }}
      run: pytest -k ${{ matrix.component }} -m testcases
