name: VHD tests
'on':
  workflow_dispatch: {}
  push:
    paths:
    - src/**
    - test/**
    - .github/workflows/vhd_tests.yml

jobs:
  test:
    name: Test ${{ matrix.component }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [GENERIC_ADDER, GENERIC_COUNTER, GENERIC_DEBOUNCE, GENERIC_EDGE_DETECTOR, GENERIC_FLIP_FLOP, GENERIC_MUX_2X1, GENERIC_MUX_4X1, GENERIC_RAM, GENERIC_REGISTER, GENERIC_ROM, GENERIC_SIGNAL_EXTENDER, MODULE_ALU, MODULE_ALU_CONTROLLER, MODULE_CONTROL_UNIT, MODULE_PC, MODULE_REGISTER_FILE, MODULE_WRITE_BACK, RV32I_ALU, RV32I_ALU_BIT, RV32I_ALU_CONTROLLER, RV32I_INSTRUCTION_DECODER, RV32I_REGISTER_FILE, STAGE_EX, STAGE_ID, STAGE_IF, STAGE_MEM, STAGE_WB, TOP_LEVEL]
        test_cases: [true, true, false, true, true, true, true, true, true, true, false, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, true]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install GHDL
      uses: ghdl/setup-ghdl-ci@nightly
      with:
        backend: llvm
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: pip
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run Synthesis
      run: pytest -k ${{ matrix.component }} -m synthesis
    - name: Run Test Cases
      if: ${{ contains(matrix.test_cases, true) }}
      run: pytest -k ${{ matrix.component }} -m testcases
