name: Run tests
'on':
  workflow_dispatch: {}
  push:
    paths:
    - src/**
    - test/**
    - .github/workflows/vhdl_tests.yml
jobs:
  setup-env:
    name: Setup environment
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install GHDL
      uses: ghdl/setup-ghdl-ci@nightly
      with:
        backend: llvm
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: pip
    - name: Install dependencies
      run: pip install -r requirements.txt
  GENERIC_ADDER:
    name: GENERIC_ADDER
    needs: setup-env
    runs-on: ubuntu-latest
    steps:
    - name: GENERIC_ADDER
      run: pytest -k GENERIC_ADDER
  GENERIC_COUNTER:
    name: GENERIC_COUNTER
    needs: setup-env
    runs-on: ubuntu-latest
    steps:
    - name: GENERIC_COUNTER
      run: pytest -k GENERIC_COUNTER
  GENERIC_DEBOUNCE:
    name: GENERIC_DEBOUNCE
    needs: setup-env
    runs-on: ubuntu-latest
    steps:
    - name: GENERIC_DEBOUNCE
      run: pytest -k GENERIC_DEBOUNCE
  GENERIC_EDGE_DETECTOR:
    name: GENERIC_EDGE_DETECTOR
    needs: setup-env
    runs-on: ubuntu-latest
    steps:
    - name: GENERIC_EDGE_DETECTOR
      run: pytest -k GENERIC_EDGE_DETECTOR
  GENERIC_FLIP_FLOP:
    name: GENERIC_FLIP_FLOP
    needs: setup-env
    runs-on: ubuntu-latest
    steps:
    - name: GENERIC_FLIP_FLOP
      run: pytest -k GENERIC_FLIP_FLOP
  GENERIC_MUX_2X1:
    name: GENERIC_MUX_2X1
    needs: setup-env
    runs-on: ubuntu-latest
    steps:
    - name: GENERIC_MUX_2X1
      run: pytest -k GENERIC_MUX_2X1
  GENERIC_MUX_4X1:
    name: GENERIC_MUX_4X1
    needs: setup-env
    runs-on: ubuntu-latest
    steps:
    - name: GENERIC_MUX_4X1
      run: pytest -k GENERIC_MUX_4X1
  GENERIC_RAM:
    name: GENERIC_RAM
    needs: setup-env
    runs-on: ubuntu-latest
    steps:
    - name: GENERIC_RAM
      run: pytest -k GENERIC_RAM
  GENERIC_REGISTER:
    name: GENERIC_REGISTER
    needs: setup-env
    runs-on: ubuntu-latest
    steps:
    - name: GENERIC_REGISTER
      run: pytest -k GENERIC_REGISTER
  GENERIC_ROM:
    name: GENERIC_ROM
    needs: setup-env
    runs-on: ubuntu-latest
    steps:
    - name: GENERIC_ROM
      run: pytest -k GENERIC_ROM
  GENERIC_SIGNAL_EXTENDER:
    name: GENERIC_SIGNAL_EXTENDER
    needs: setup-env
    runs-on: ubuntu-latest
    steps:
    - name: GENERIC_SIGNAL_EXTENDER
      run: pytest -k GENERIC_SIGNAL_EXTENDER
  MODULE_ALU:
    name: MODULE_ALU
    needs: setup-env
    runs-on: ubuntu-latest
    steps:
    - name: MODULE_ALU
      run: pytest -k MODULE_ALU
  MODULE_ALU_CONTROLLER:
    name: MODULE_ALU_CONTROLLER
    needs: setup-env
    runs-on: ubuntu-latest
    steps:
    - name: MODULE_ALU_CONTROLLER
      run: pytest -k MODULE_ALU_CONTROLLER
  MODULE_CONTROL_UNIT:
    name: MODULE_CONTROL_UNIT
    needs: setup-env
    runs-on: ubuntu-latest
    steps:
    - name: MODULE_CONTROL_UNIT
      run: pytest -k MODULE_CONTROL_UNIT
  MODULE_PC:
    name: MODULE_PC
    needs: setup-env
    runs-on: ubuntu-latest
    steps:
    - name: MODULE_PC
      run: pytest -k MODULE_PC
  MODULE_REGISTER_FILE:
    name: MODULE_REGISTER_FILE
    needs: setup-env
    runs-on: ubuntu-latest
    steps:
    - name: MODULE_REGISTER_FILE
      run: pytest -k MODULE_REGISTER_FILE
  MODULE_WRITE_BACK:
    name: MODULE_WRITE_BACK
    needs: setup-env
    runs-on: ubuntu-latest
    steps:
    - name: MODULE_WRITE_BACK
      run: pytest -k MODULE_WRITE_BACK
  RV32I_ALU:
    name: RV32I_ALU
    needs: setup-env
    runs-on: ubuntu-latest
    steps:
    - name: RV32I_ALU
      run: pytest -k RV32I_ALU
  RV32I_ALU_BIT:
    name: RV32I_ALU_BIT
    needs: setup-env
    runs-on: ubuntu-latest
    steps:
    - name: RV32I_ALU_BIT
      run: pytest -k RV32I_ALU_BIT
  RV32I_ALU_CONTROLLER:
    name: RV32I_ALU_CONTROLLER
    needs: setup-env
    runs-on: ubuntu-latest
    steps:
    - name: RV32I_ALU_CONTROLLER
      run: pytest -k RV32I_ALU_CONTROLLER
  RV32I_INSTRUCTION_DECODER:
    name: RV32I_INSTRUCTION_DECODER
    needs: setup-env
    runs-on: ubuntu-latest
    steps:
    - name: RV32I_INSTRUCTION_DECODER
      run: pytest -k RV32I_INSTRUCTION_DECODER
  RV32I_REGISTER_FILE:
    name: RV32I_REGISTER_FILE
    needs: setup-env
    runs-on: ubuntu-latest
    steps:
    - name: RV32I_REGISTER_FILE
      run: pytest -k RV32I_REGISTER_FILE
  STAGE_EX:
    name: STAGE_EX
    needs: setup-env
    runs-on: ubuntu-latest
    steps:
    - name: STAGE_EX
      run: pytest -k STAGE_EX
  STAGE_ID:
    name: STAGE_ID
    needs: setup-env
    runs-on: ubuntu-latest
    steps:
    - name: STAGE_ID
      run: pytest -k STAGE_ID
  STAGE_IF:
    name: STAGE_IF
    needs: setup-env
    runs-on: ubuntu-latest
    steps:
    - name: STAGE_IF
      run: pytest -k STAGE_IF
  STAGE_MEM:
    name: STAGE_MEM
    needs: setup-env
    runs-on: ubuntu-latest
    steps:
    - name: STAGE_MEM
      run: pytest -k STAGE_MEM
  STAGE_WB:
    name: STAGE_WB
    needs: setup-env
    runs-on: ubuntu-latest
    steps:
    - name: STAGE_WB
      run: pytest -k STAGE_WB
  TOP_LEVEL:
    name: TOP_LEVEL
    needs: setup-env
    runs-on: ubuntu-latest
    steps:
    - name: TOP_LEVEL
      run: pytest -k TOP_LEVEL
