name: VHD stress testing routine
'on':
  workflow_dispatch: {}

jobs:
  test:
    name: Test ${{ matrix.component }}
    runs-on: ubuntu-latest
    container:
      image: hdlc/ghdl:yosys
    strategy:
      matrix:
          include:
          - component: CPU_EXECUTION_FOWARDING_UNIT
            enabled: true
          - component: CPU_LOAD_EXTENDER
            enabled: false
          - component: CPU_STAGE_EX
            enabled: false
          - component: CPU_STAGE_ID
            enabled: false
          - component: CPU_STAGE_IF
            enabled: false
          - component: CPU_STAGE_MEM
            enabled: false
          - component: CPU_STAGE_WB
            enabled: false
          - component: CPU_STORE_EXTENDER
            enabled: false
          - component: CPU_TOP_LEVEL
            enabled: false
          - component: GENERIC_ADDER
            enabled: false
          - component: GENERIC_COMPARATOR
            enabled: false
          - component: GENERIC_DEBOUNCE
            enabled: false
          - component: GENERIC_EDGE_DETECTOR
            enabled: false
          - component: GENERIC_FLIP_FLOP
            enabled: false
          - component: GENERIC_MUX_2X1
            enabled: false
          - component: GENERIC_MUX_4X1
            enabled: false
          - component: GENERIC_RAM
            enabled: false
          - component: GENERIC_REGISTER
            enabled: false
          - component: GENERIC_ROM
            enabled: false
          - component: GENERIC_SIGNAL_EXTENDER
            enabled: false
          - component: MODULE_BRANCH_COMPARE_UNIT
            enabled: false
          - component: MODULE_BRANCH_UNIT
            enabled: false
          - component: MODULE_CONTROL_UNIT
            enabled: false
          - component: MODULE_EXECUTION_UNIT_CONTROLLER
            enabled: false
          - component: MODULE_EXECUTION_UNIT
            enabled: false
          - component: MODULE_PROGRAM_COUNTER
            enabled: false
          - component: MODULE_REGISTER_FILE
            enabled: false
          - component: MODULE_WRITE_BACK
            enabled: false
          - component: RV32I_ALU_BIT
            enabled: false
          - component: RV32I_ALU_CONTROLLER
            enabled: false
          - component: RV32I_ALU_SHIFTER
            enabled: false
          - component: RV32I_ALU
            enabled: false
          - component: RV32I_BRANCH_CONTROLLER
            enabled: false
          - component: RV32I_REGISTER_FILE
            enabled: false
          - component: TOP_LEVEL
            enabled: false
    steps:
    - name: Set up environment
      run: |
        apt-get update
        apt-get install lsb_release
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: pip
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        npm install -g netlistsvg
    - name: Run Synthesis
      run: pytest -k ${{ matrix.component }} -m synthesis
    - name: Run Testcases
      if: ${{ contains(matrix.test_cases, true) }}
      run: pytest -k ${{ matrix.component }} -m sress
