name: VHDL-TESTS

on:
  push:
  pull_request:
    
jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ghdl: [latest]
        gtkwave: [latest]
        python: [latest]
    name: VHDLtest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      
      - name: install dependencies
        run: pip install -r requirements.txt
    
      - name: Run tests
        run: SIM=ghdl pytest -s
